---
apiVersion: v1
kind: ConfigMap
metadata:
  name: slurm-config
data:
  slurm.conf: |
    ClusterName=linux
    SlurmctldHost=slurmctld
    SlurmUser=slurm
    SlurmdUser=root
    StateSaveLocation=/var/spool/slurmctld
    SlurmdSpoolDir=/var/spool/slurmd
    ReturnToService=1
    
    # Preemption
    PreemptMode=REQUEUE
    PreemptType=preempt/partition_prio
    
    # Nodos
    NodeName=c[1-4] CPUs=2 RealMemory=1000 State=UNKNOWN
    
    # Particiones con prioridad (PriorityTier)
    PartitionName=normal Nodes=c[1-4] Default=YES PriorityTier=1 State=UP
    PartitionName=rapida Nodes=c[1-4] Default=NO  PriorityTier=10 State=UP
